- name: Add Helm repository for ARC (actions-runner-controller)
  kubernetes.core.helm_repository:
    name: actions-runner-controller
    repo_url: https://actions-runner-controller.github.io/actions-runner-controller

- name: Deploy or upgrade ARC (actions-runner-controller) via Helm
  kubernetes.core.helm:
    name: actions-runner-controller
    chart_ref: actions-runner-controller/actions-runner-controller
    release_namespace: actions-runner-system
    create_namespace: true
    values_files:
      - "{{ role_path }}/templates/arc-values.yaml"
    values:
      authSecret:
        create: true
        github_token: "{{ github_token }}"
    wait: true
